"use client";
import {useEffect,useMemo,useState} from "react";
import {api} from "@/lib/api";
import Link from "next/link";

type FormState={monthly_cap:number;target_cost_per_video:number;duration_seconds:number;scene_count:number;clip_seconds:number;idea_count:number;privacy_status:string;text_provider:string;research_provider:string;video_provider:string;voice_provider:string;renderer_provider:string;publisher_provider:string;openai_model:string;runway_model:string;elevenlabs_voice_id:string;elevenlabs_model_id:string;hard_stop_on_cap:boolean};
const empty:FormState={monthly_cap:100,target_cost_per_video:2.5,duration_seconds:30,scene_count:6,clip_seconds:5,idea_count:10,privacy_status:"private",text_provider:"mock",research_provider:"mock",video_provider:"mock",voice_provider:"mock",renderer_provider:"mock",publisher_provider:"mock",openai_model:"",runway_model:"",elevenlabs_voice_id:"",elevenlabs_model_id:"",hard_stop_on_cap:true};
const label=(x:string)=>x.replaceAll("_"," ").replace(/\b\w/g,m=>m.toUpperCase());

export default function Settings(){
 const [cfg,setCfg]=useState<any>(null),[status,setStatus]=useState<any>({}),[budget,setBudget]=useState<any>(null),[form,setForm]=useState<FormState>(empty),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 async function load(){const [r,s,b]=await Promise.all([api<any>("/api/settings/runtime"),api<any>("/api/providers/status"),api<any>("/api/budget/status")]);const c=r.effective;setCfg(c);setStatus(s);setBudget(b);setForm({monthly_cap:Number(c.budgets?.monthly_cap??100),target_cost_per_video:Number(c.budgets?.target_cost_per_video??2.5),duration_seconds:Number(c.video_defaults?.duration_seconds??30),scene_count:Number(c.video_defaults?.scene_count??6),clip_seconds:Number(c.video_defaults?.clip_seconds??5),idea_count:Number(c.content?.idea_count??10),privacy_status:c.provider_options?.youtube?.privacy_status??"private",text_provider:c.providers?.text??"mock",research_provider:c.providers?.research??"mock",video_provider:c.providers?.video??"mock",voice_provider:c.providers?.voice??"mock",renderer_provider:c.providers?.renderer??"mock",publisher_provider:c.providers?.publisher??"mock",openai_model:c.provider_options?.openai?.model??"",runway_model:c.provider_options?.runway?.model??"",elevenlabs_voice_id:c.provider_options?.elevenlabs?.voice_id??"",elevenlabs_model_id:c.provider_options?.elevenlabs?.model_id??"",hard_stop_on_cap:!!c.budgets?.hard_stop_on_cap});}
 useEffect(()=>{load().catch(e=>setMessage(String(e)))},[]);
 const set=(k:keyof FormState,v:any)=>setForm(x=>({...x,[k]:v}));
 async function save(){setBusy(true);setMessage("");try{await api("/api/settings/runtime",{method:"PUT",body:JSON.stringify(form)});await load();setMessage("Saved. New projects will use these settings.")}catch(e:any){setMessage(e.message)}finally{setBusy(false)}}
 const liveCount=useMemo(()=>Object.values(status).filter((v:any)=>v.provider!=="mock"&&v.configured).length,[status]);
 if(!cfg)return <section className="hero"><h1>Loading <em>settings…</em></h1><p>{message}</p></section>;
 return <>
  <section className="hero"><div className="badge">Phone Control Center</div><h1 className="mobileHeadline">Studio <em>Settings</em></h1><p>Change normal production settings here from your phone. API secrets stay in your hosting provider's encrypted environment variables.</p><Link className="btn" href="/setup">View one-time setup guide</Link></section>
  {message&&<div className={message.startsWith("Saved")?"success":"notice"}>{message}</div>}
  <div className="grid grid-2" style={{marginTop:14}}>
   <section className="card"><div className="row space"><h2 className="sectionTitle">Connections</h2><span className="badge green">{liveCount} live</span></div>{Object.entries(status).map(([kind,v]:any)=><div className="providerCard" key={kind}><div><strong>{label(kind)}</strong><div className="providerHint">{v.provider==="mock"?"Demo mode — no credits used":v.configured?`${v.provider} is ready`:`Add ${v.secret_required||"required setup"} in hosting environment variables`}</div></div><span className={`badge ${v.configured?"green":"amber"}`}>{v.configured?v.provider==="mock"?"Demo":"Ready":"Setup"}</span></div>)}<p className="muted" style={{fontSize:13}}>For the first deployment, keep every provider on <strong>mock</strong>. Then switch them live one at a time.</p></section>
   <section className="card"><h2 className="sectionTitle">Budget guardrails</h2><div className="formGrid"><Field label="Monthly cap ($)"><input className="input" inputMode="decimal" type="number" value={form.monthly_cap} onChange={e=>set("monthly_cap",Number(e.target.value))}/></Field><Field label="Target / video ($)"><input className="input" inputMode="decimal" type="number" value={form.target_cost_per_video} onChange={e=>set("target_cost_per_video",Number(e.target.value))}/></Field></div><label className="row" style={{marginTop:14}}><input type="checkbox" checked={form.hard_stop_on_cap} onChange={e=>set("hard_stop_on_cap",e.target.checked)}/><span><strong>Hard stop at budget cap</strong><div className="muted" style={{fontSize:12}}>Recommended while testing.</div></span></label>{budget&&<><div className="progress" style={{marginTop:14}}><span style={{width:`${Math.min(100,budget.cap?budget.spent/budget.cap*100:0)}%`}}/></div><p className="muted">Spent ${Number(budget.spent).toFixed(2)} · ${Number(budget.remaining).toFixed(2)} remaining</p></>}</section>
   <section className="card"><h2 className="sectionTitle">Video defaults</h2><div className="formGrid"><Field label="Length (seconds)"><input className="input" type="number" value={form.duration_seconds} onChange={e=>set("duration_seconds",Number(e.target.value))}/></Field><Field label="Scenes"><input className="input" type="number" value={form.scene_count} onChange={e=>set("scene_count",Number(e.target.value))}/></Field><Field label="Seconds / scene"><input className="input" type="number" value={form.clip_seconds} onChange={e=>set("clip_seconds",Number(e.target.value))}/></Field><Field label="Ideas per batch"><input className="input" type="number" value={form.idea_count} onChange={e=>set("idea_count",Number(e.target.value))}/></Field></div></section>
   <section className="card"><h2 className="sectionTitle">Provider routing</h2><div className="formGrid"><Select label="Writing" value={form.text_provider} onChange={v=>set("text_provider",v)} values={["mock","openai"]}/><Select label="Research" value={form.research_provider} onChange={v=>set("research_provider",v)} values={["mock","openai"]}/><Select label="Video" value={form.video_provider} onChange={v=>set("video_provider",v)} values={["mock","runway"]}/><Select label="Voice" value={form.voice_provider} onChange={v=>set("voice_provider",v)} values={["mock","elevenlabs"]}/><Select label="Renderer" value={form.renderer_provider} onChange={v=>set("renderer_provider",v)} values={["mock","ffmpeg"]}/><Select label="Publisher" value={form.publisher_provider} onChange={v=>set("publisher_provider",v)} values={["mock","youtube"]}/></div></section>
   <section className="card"><h2 className="sectionTitle">Models & voice</h2><div className="stack"><Field label="OpenAI model"><input className="input" value={form.openai_model} onChange={e=>set("openai_model",e.target.value)}/></Field><Field label="Runway model"><input className="input" value={form.runway_model} onChange={e=>set("runway_model",e.target.value)}/></Field><Field label="ElevenLabs voice ID"><input className="input" value={form.elevenlabs_voice_id} onChange={e=>set("elevenlabs_voice_id",e.target.value)}/></Field><Field label="ElevenLabs model"><input className="input" value={form.elevenlabs_model_id} onChange={e=>set("elevenlabs_model_id",e.target.value)}/></Field></div></section>
   <section className="card"><h2 className="sectionTitle">YouTube defaults</h2><Select label="New upload visibility" value={form.privacy_status} onChange={v=>set("privacy_status",v)} values={["private","unlisted","public"]}/><div className="notice" style={{marginTop:14}}>Keep this on <strong>Private</strong> until YouTube publishing is fully tested. The workflow still requires final approval.</div></section>
  </div>
  <div className="savebar"><button className="btn primary tap" style={{width:"100%"}} disabled={busy} onClick={save}>{busy?"Saving…":"Save Studio Settings"}</button></div>
 </>;
}
function Field({label,children}:{label:string,children:React.ReactNode}){return <label><span className="fieldLabel">{label}</span>{children}</label>}
function Select({label,value,onChange,values}:{label:string,value:string,onChange:(v:string)=>void,values:string[]}){return <Field label={label}><select className="input" value={value} onChange={e=>onChange(e.target.value)}>{values.map(x=><option key={x} value={x}>{labelize(x)}</option>)}</select></Field>}
function labelize(x:string){return x.replaceAll("_"," ").replace(/\b\w/g,m=>m.toUpperCase())}
